version: '3.8'

services:
  arangodb:
    image: arangodb:3.11.4
    container_name: arangodb-hello
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: password
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps:/var/lib/arangodb3-apps
    networks:
      - hello-network

networks:
  hello-network:
    driver: bridge

volumes:
  arangodb_data:
  arangodb_apps: